version: "3"

services:
  # mysql
  mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: users-worker
      MYSQL_DATABASE: users-worker
  # redis
  redis:
    image: redis:6
    restart: always
    ports:
    - 6379:6379
