version: "3"

services:
  # mongo
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users-worker
  # redis
  redis:
    image: redis:6
    restart: always
    ports:
    - 6379:6379
